image: golang:1.20

stages:
    - test

before_script:
    - go install gotest.tools/gotestsum@v1.10.0

unit_tests:
    stage: test
    script:
        - gotestsum --junitfile unit-tests.xml --packages="./..." -- -coverprofile coverage.out
        - go tool cover -func coverage.out
    coverage: /total:\s+\(statements\)\s+(\d+\.\d+)%/
    artifacts:
        reports:
            junit:
                - 'unit-tests.xml'