image: golang:1.20

stages:
    - test

lint:
    stage: test
    script:
        - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
        - golangci-lint run

unit_tests:
    stage: test
    script:
        - go install gotest.tools/gotestsum@v1.10.0
        - gotestsum --junitfile unit-tests.xml --packages="./..." -- -coverprofile coverage.out
        - go tool cover -func coverage.out
    coverage: /total:\s+\(statements\)\s+(\d+\.\d+)%/
    artifacts:
        reports:
            junit:
                - 'unit-tests.xml'